version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: "example"
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:

